BEGIN TRANSACTION INSERT_NW_PROJECTS

    CREATE TABLE NW_PROJECTS (
        NW_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
        ProjectName NVARCHAR(MAX)
    ); 

    INSERT INTO NW_PROJECTS (ProjectName)
        VALUES 
        ('Pioneer Group'),
		('TEST')

ROLLBACK TRANSACTION INSERT_NW_PROJECTS
--COMMIT TRANSACTION INSERT_NW_PROJECTS