BEGIN TRANSACTION INSERT_SAC_SUPPORT_ACCESS_CALL

CREATE TABLE SAC_SUPPORT_ACCESS_CALL (
		SAC_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SAC_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SAC_SUPPORT_ACCESS_CALL
VALUES
	('1'),
    ('2'),
    ('3'),
    ('Supply Only'),
    ('Handed Back')

	SELECT * FROM SAC_SUPPORT_ACCESS_CALL

ROLLBACK TRANSACTION INSERT_SAC_SUPPORT_ACCESS_CALL
--COMMIT TRANSACTION INSERT_SAC_SUPPORT_ACCESS_CALL