BEGIN TRANSACTION INSERT_SAE_SUPPORT_ACCESS_EQUIPMENT

CREATE TABLE SAE_SUPPORT_ACCESS_EQUIPMENT (
		SAE_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SAE_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SAE_SUPPORT_ACCESS_EQUIPMENT
VALUES
	('Independent Scaffold'),
    ('Tower Scaffold'),
    ('MEWP'),
    ('Jammer System')

	SELECT * FROM SAE_SUPPORT_ACCESS_EQUIPMENT

ROLLBACK TRANSACTION INSERT_SAE_SUPPORT_ACCESS_EQUIPMENT
--COMMIT TRANSACTION INSERT_SAE_SUPPORT_ACCESS_EQUIPMENT