BEGIN TRANSACTION INSERT_SCT_SUPPORT_CONSTRUCTION_TYPE

CREATE TABLE SCT_SUPPORT_CONSTRUCTION_TYPE (
		SCT_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SCT_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SCT_SUPPORT_CONSTRUCTION_TYPE
VALUES
    ('EWI'),
    ('No Fines'),
    ('IWI'),
    ('Brick'),
    ('Brick & Render'),
    ('Render'),
    ('Peddle Dash'),
    ('Timber'),
    ('Brick & Cladding')

	SELECT * FROM SCT_SUPPORT_CONSTRUCTION_TYPE

ROLLBACK TRANSACTION INSERT_SCT_SUPPORT_CONSTRUCTION_TYPE
--COMMIT TRANSACTION INSERT_SCT_SUPPORT_CONSTRUCTION_TYPE