BEGIN TRANSACTION INSERT_SD_SUPPORT_DISABIILITY

CREATE TABLE SD_SUPPORT_DISABIILITY (
		SD_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SD_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SD_SUPPORT_DISABIILITY
VALUES
    ('Vision'),
    ('Violent'),
    ('Mobility Issues'),
    ('Communicating'),
    ('Hearing'),
    ('Life Limiting Illness'),
    ('Mental Health'),
    ('Breathing Difficulties')

	SELECT * FROM SD_SUPPORT_DISABIILITY

ROLLBACK TRANSACTION INSERT_SD_SUPPORT_DISABIILITY
--COMMIT TRANSACTION INSERT_SD_SUPPORT_DISABIILITY