BEGIN TRANSACTION INSERT_SDP_SUPPORT_DELIVERY_POINT

CREATE TABLE SDP_SUPPORT_DELIVERY_POINT (
		SDP_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SDP_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SDP_SUPPORT_DELIVERY_POINT
VALUES
    ('Depot'),
    ('Container')

	SELECT * FROM SDP_SUPPORT_DELIVERY_POINT

ROLLBACK TRANSACTION INSERT_SDP_SUPPORT_DELIVERY_POINT
--COMMIT TRANSACTION INSERT_SDP_SUPPORT_DELIVERY_POINT