BEGIN TRANSACTION INSERT_SI_SUPPORT_INSTALLERS

CREATE TABLE SI_SUPPORT_INSTALLERS (
		SI_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SI_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SI_SUPPORT_INSTALLERS
VALUES
    ('Brian Gordon'),
    ('Alex Clark'),
    ('Julian Abbey '),
    ('Dave Bennett'),
    ('Neil Bucknall'),
    ('Jim McDonald'),
    ('Eric'),
    ('Adrian')

	SELECT * FROM SI_SUPPORT_INSTALLERS

ROLLBACK TRANSACTION INSERT_SI_SUPPORT_INSTALLERS
--COMMIT TRANSACTION INSERT_SI_SUPPORT_INSTALLERS