BEGIN TRANSACTION Data_Override_SP_SUPPORT

	INSERT INTO SP_SUPPORT (SP_VALUE,SP_SPC_FK)
	VALUES 
	('COMMENCEMENT PENDING',1),
	('ON HOLD',1),
	('SURVEY BOOKED',1),
	('SCOPE SURVEY',1),
	('SURVEY RECEIVED',1),
	('PM TO CLEANSE',1),
	('Survey In Vision, PM to clean',1),
	('CLEANSED',1),
	('SENT FOR PRICING',1),
	('PRICED',1),
	('AWAIT CLIENT APPROVAL',1),
	('CALLED OFF',1),
	('DELIVERED TO DEPOT/CONTAINER',1),
	('BOOKED TO FIT',1),
	('PART FITTED',1),
	('FITTED',1),
	('HANDED OVER',1),
	('CANCELLED',1),
	('NWR',1),
	('NO ACCESS SURVEY',1),
	('NO ACCESS INSTALL',1),
	('REFUSAL',1),
	('HANDED BACK',1),
	('DUPLICATE',1),
	('SUPPLY ONLY',1),
	('RECALL REQUIRED',1),
	('FAILED INSTALL',1),
	('SURVEY',1),

	('1',2),
	('2',2),
	('3',2),
	('Supply Only',2),
	('Handed Back',2),

	('Independent Scaffold',3),
	('Tower Scaffold',3),
	('MEWP',3),
	('Jammer System',3),

	('EWI',4),
	('No Fines',4),
	('IWI',4),
	('Brick',4),
	('Brick & Render',4),
	('Render',4),
	('Peddle Dash',4),
	('Timber',4),
	('Brick & Cladding',4),
	
	('House',5),
	('Flat',5),
	('Bungalow',5),
	('Communal',5),
	('Terrace',5),

	('Vision',6),
	('Violent',6),
	('Mobility Issues',6),
	('Communicating',6),
	('Hearing',6),
	('Life Limiting Illness',6),
	('Mental Health',6),
	('Breathing Difficulties',6),

	('7:30am',7),
	('8am to 10am',7),
	('8am to 12 noon',7),
	('8am to 2pm',7),
	('9am to 1pm',7),
	('9am to 3pm',7),
	('10am to 2pm',7),
	('10am to 3pm',7),
	('11am to 3pm',7),
	('12 noon to 4pm',7),
	('1pm To 5pm',7),
	('AM',7),
	('PM',7),
	('First Call',7),

	('A Lethridge',8),
	('A Meldrum',8),
	('B Sinclair',8),
	('I Roy',8),
	('P Beahan',8),
	('S Burgess',8),
	('Tony Lee',8),
	('Mick Clingan',8),
	('M Turpin',8),
	('D Ansell',8),

	('CLIENT ISSUE',9),
	('SEE COMMENTS',9),
	('DOOR CHOICE',9),
	('FIRE PRODUCTS; ON HOLD',9),
	('UPRN Missing',9),
	('Asbestos Report Required',9),
	('Lintel Required',9),
	('Door Query, see comments',9),
	('Awaiting all paperwork',9),
	('Photos rec''d, await survey.',9),
	('Survey Rec''d, awaiting photos',9),
	('Survey with surveyor',9),
	('Aluminium',9),
	('Asbestos to be removed',9),
	('Await survey to be cleansed',9),
	('SERVICE CALL BOOKED',9),
	('CUSTOMER CARE ATTENDING',9),
	('Ready to be Called Off',9),
	('Ready to be Called Off when approved',9),
	('READY TO SEND FOR PRICING',9),
	('POST 2000',9),
	('Survey with surveyor',9),
	('Electrician Required',9),
	('Asbestos removal req''d?',9),
	('Nothing rec''d on hold with surveyor / DA',9),

	('Depot',10),
	('Container',10),

	('Brian Gordon',11),
	('Alex Clark',11),
	('Julian Abbey ',11),
	('Dave Bennett',11),
	('Neil Bucknall',11),
	('Jim McDonald',11),
	('Eric',11),
	('Adrian',11)

ROLLBACK TRANSACTION Data_Override_SP_SUPPORT
--COMMIT TRANSACTION Data_Override_SP_SUPPORT