BEGIN TRANSACTION INSERT_SP_SUPPORT

CREATE TABLE SP_SUPPORT (
		SP_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SP_VALUE NVARCHAR(MAX),
		SP_SPC_FK int FOREIGN KEY REFERENCES SPC_SUPPORT_CATEGORY(SPC_PK),
	); 

ROLLBACK TRANSACTION INSERT_SP_SUPPORT
--COMMIT TRANSACTION INSERT_SP_SUPPORT