BEGIN TRANSACTION INSERT_SPA_SUPPORT_PROPERTY_ARCHETYPE

CREATE TABLE SPA_SUPPORT_PROPERTY_ARCHETYPE (
		SPA_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SPA_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SPA_SUPPORT_PROPERTY_ARCHETYPE
VALUES
    ('House'),
    ('Flat'),
    ('Bungalow'),
    ('Communal'),
    ('Terrace')

	SELECT * FROM SPA_SUPPORT_PROPERTY_ARCHETYPE

ROLLBACK TRANSACTION INSERT_SPA_SUPPORT_PROPERTY_ARCHETYPE
--COMMIT TRANSACTION INSERT_SPA_SUPPORT_PROPERTY_ARCHETYPE