BEGIN TRANSACTION INSERT_SS_SUPPORT_STATUS

CREATE TABLE SS_SUPPORT_STATUS (
		SS_PK int NOT NULL IDENTITY(1,1) PRIMARY KEY,
		SS_Category_Name NVARCHAR(MAX),
	); 

INSERT INTO SS_SUPPORT_STATUS
VALUES
	('COMMENCEMENT PENDING'),
    ('ON HOLD'),
    ('SURVEY BOOKED'),
    ('SCOPE SURVEY'),
    ('SURVEY RECEIVED'),
    ('PM TO CLEANSE'),
    ('Survey In Vision, PM to clean'),
    ('CLEANSED'),
    ('SENT FOR PRICING'),
    ('PRICED'),
    ('AWAIT CLIENT APPROVAL'),
    ('CALLED OFF'),
    ('DELIVERED TO DEPOT/CONTAINER'),
    ('BOOKED TO FIT'),
    ('PART FITTED'),
    ('FITTED'),
    ('HANDED OVER'),
    ('CANCELLED'),
    ('NWR'),
    ('NO ACCESS SURVEY'),
    ('NO ACCESS INSTALL'),
    ('REFUSAL'),
    ('HANDED BACK'),
    ('DUPLICATE'),
    ('SUPPLY ONLY'),
    ('RECALL REQUIRED'),
    ('FAILED INSTALL'),
    ('SURVEY')

	SELECT * FROM SS_SUPPORT_STATUS

ROLLBACK TRANSACTION INSERT_SS_SUPPORT_STATUS
--COMMIT TRANSACTION INSERT_SS_SUPPORT_STATUS